### ISSUE TITLE
Colon and backslash (break) does not work with formatting

### ISSUE THREAD

**Issue by jjmurre** [rtfd/CommonMark-py#109]
The following markdown is not rendered correctly as html:

    *text:*\
    next line

The rendered html contains the *:

    <p>*text:*nextline</p>

**Comment by nikolas** [comment]
It looks like there's an ambiguity in the commonmark spec, as commonmark.js renders this slightly differently: http://spec.commonmark.org/dingus/

You could raise this in the CommonMark discussion forum to come up with some well-defined behavior for this: https://talk.commonmark.org/

This library just follows the behavior defined in `spec.txt` - if everything's working according to that, then it's not considered a bug, so I'm going to close this issue here.
