### ISSUE TITLE
Forking CommonMark-py?

### ISSUE THREAD

**Issue by nikolas** [rtfd/CommonMark-py#11]
I haven't put much time into upstream CommonMark compatibility on this repository, but in the meantime do you think it would be worth making this a more official fork of CommonMark-py, since that project doesn't seem to be going anywhere?

That way, we could start publishing these changes on pypi, something like: https://pypi.python.org/pypi/CommonMark2

**Comment by lu-zero** [comment]
Makes sense indeed.

**Comment by lu-zero** [comment]
@ericholscher is it a problem if I open a tree about CommonMark2-py on @rtfd ?

**Comment by ericholscher** [comment]
Seems like a reasonable approach, since it seems inactive on the main repo.

**Comment by ericholscher** [comment]
I'd like if we could not fork the name, and just keep `commonmark` in python be a reasonable install, but if that isn't something that can happen, I guess having `commonmark2` on PyPI is okay.

**Comment by nikolas** [comment]
In order to keep the `commonmark` name we would need to have admin access to the original pypi package. It looks like @rolandshoemaker or @kafle could handle that.

**Comment by rolandshoemaker** [comment]
Hey guys, really sorry I've been ignoring this for so long, I started a new job around 6 months ago and I've been absolutely swamped. Looks like you guys are doing good work on the project which I don't have time to do so I'm happy to transfer the PyPi stuff over to you guys and stick a notice on my repo directing people here since both still seem to get a bunch of traffic but are unmaintained (not really sure about how to do the PyPi stuff but will look into it ASAP).

**Comment by svetlyak40wt** [comment]
:+1:

**Comment by nikolas** [comment]
That's cool.. yeah it would be great if @lu-zero or whoever wants to was able make new releases and put them on https://pypi.python.org/pypi/CommonMark

Then there's a better possibility of someone getting this library working with the newer commonmark specs. Let us know when you get a chance to add us to the repo. My pypi username is nnyby.

**Comment by ericholscher** [comment]
My pypi username is `ericholscher` -- Happy to handle releases as well. You can add people from this page: https://pypi.python.org/pypi?:action=role_form&package_name=commonmark

**Comment by lu-zero** [comment]
The repository moved to @rtfd I hope I got the procedure right.

**Comment by ericholscher** [comment]
Looks good -- the only question is if we want to preserve the `forked from` at the top. If we create the repo fresh it won't contain that forked from status, which makes it look non-canonical. I imagine that if the original repo is deleted, the forked from status will also disappear.

**Comment by lu-zero** [comment]
I guess so, anything is fine since the project is quite young.

**Comment by nikolas** [comment]
An alternative to deleting the original repo could be putting a notice up there linking to this one. For example, a similar thing happened to factory_boy: https://github.com/dnerdy/factory_boy

But yeah, there would still be the "forked from" link at the top. I'm fine with whatever, we could see how the original author feels.

**Comment by ericholscher** [comment]
@rolandshoemaker Would be great to get access to the PyPI release, as we're hoping to get 0.5.5 out the door, and get it publicly released. I know you don't have a huge amount of time, but you should be able to go to  https://pypi.python.org/pypi?:action=role_form&package_name=commonmark & just add `ericholscher` and `nnyby` is maintainers it would be awesome :fireworks:

**Comment by nikolas** [comment]
I created a pypi support request here: https://sourceforge.net/p/pypi/support-requests/573/  We might be able to get access that way.

**Comment by rolandshoemaker** [comment]
Hey guys, *extremely* sorry this has taken so long, I've had to travel a lot recently due to family stuff and have been very distracted.

Just added you both to the PyPi page as maintainers so that you can release updates via that channel, and have added a notice to `rolandshoemaker/commonmark-py` that says the following

**NOTE:** This repo is no longer maintained and most likely contains numerous bugs, for the up to date and safe version you want [`rtfd/CommonMark-py`](https://github.com/rtfd/CommonMark-py).

If there is anything else I can do to make this easier let me know!

**Comment by nikolas** [comment]
Ah I understand, thanks a lot - everything looks good.
