### ISSUE TITLE
Render plain text from AST

### ISSUE THREAD

**Issue by JoshData** [rtfd/CommonMark-py#65]
Similar to #63, I'm wondering if it would be in scope to add a plain-text renderer, which would generate nice looking plain text output from the AST.

I put together:

https://github.com/JoshData/commonmark-py-plaintext

This is different from CommonMark output: Links, for instance, are represented in a way that's understandable by people who don't know CommonMark, rather than in the \[]()-style notation. Other than that, it mostly just normalizes headings, indentation, etc. It could be revised to generate actual CommonMark.

I'd be glad to see this integrated into this project.

**Comment by ericholscher** [comment]
I'm of two minds of this kind of thing. I think in general it's good to enable an ecosystem of projects, so that we don't need to ship all these extensions with the core. I've seen a lot of success with projects built that way, with the trend being taking more of the core functionality out of the default repo/distribution, and enabling a large set of extensions that are more powerful because the core is extensible.

I do think this is useful (along with the commonmark output), so might be worth shipping in core -- the main issue I have is that merging it means we'll be required to maintain it going forward, as we upgrade core.

Perhaps the best thing to do would be to start pointing at external extensions in an "official" way, and make sure these kind of extensions are easy to support in the core?

**Comment by JoshData** [comment]
I totally get what you mean about not wanting to take on the maintenance responsibility.

That said, the reason I ended up here is that I wrote a renderer over the weekend against 0.6.3, and then after unwittingly upgrading to 0.6.4 the renderer broke. If the renderer is a part of the public API, it would be nice to have a little more stability between minor releases --- and having a second renderer here would make it harder to break. If it's not a part of the public API, then it doesn't make sense to define renderers in other projects anyway.

**Comment by nikolas** [comment]
@JoshData sorry about the API breakage between minor versions. I will try to stick to more semantic versioning.. maybe I should have incremented the version to 0.7.0 instead of 0.6.4. There were many changes in this release since jgm refactored the rendering code in commonmark.js.

**Comment by JoshData** [comment]
Ok thanks. :)
